// Mocks generated by Mockito 5.4.1 from annotations
// in widget_kit_plugin/test/user_defaults_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:widget_kit_plugin/api/user_defaults.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserDefaultsAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDefaultsAPI extends _i1.Mock implements _i2.UserDefaultsAPI {
  MockUserDefaultsAPI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> setAppGroup(String? arg_appGroup) => (super.noSuchMethod(
        Invocation.method(
          #setAppGroup,
          [arg_appGroup],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<Object?> get(
    String? arg_key,
    String? arg_appGroup,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [
            arg_key,
            arg_appGroup,
          ],
        ),
        returnValue: _i3.Future<Object?>.value(),
      ) as _i3.Future<Object?>);
  @override
  _i3.Future<String?> getString(
    String? arg_key,
    String? arg_appGroup,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getString,
          [
            arg_key,
            arg_appGroup,
          ],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);
  @override
  _i3.Future<bool?> getBool(
    String? arg_key,
    String? arg_appGroup,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBool,
          [
            arg_key,
            arg_appGroup,
          ],
        ),
        returnValue: _i3.Future<bool?>.value(),
      ) as _i3.Future<bool?>);
  @override
  _i3.Future<int?> getInt(
    String? arg_key,
    String? arg_appGroup,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInt,
          [
            arg_key,
            arg_appGroup,
          ],
        ),
        returnValue: _i3.Future<int?>.value(),
      ) as _i3.Future<int?>);
  @override
  _i3.Future<double?> getDouble(
    String? arg_key,
    String? arg_appGroup,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDouble,
          [
            arg_key,
            arg_appGroup,
          ],
        ),
        returnValue: _i3.Future<double?>.value(),
      ) as _i3.Future<double?>);
  @override
  _i3.Future<Map<Object?, Object?>?> getMap(
    String? arg_key,
    String? arg_appGroup,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMap,
          [
            arg_key,
            arg_appGroup,
          ],
        ),
        returnValue: _i3.Future<Map<Object?, Object?>?>.value(),
      ) as _i3.Future<Map<Object?, Object?>?>);
  @override
  _i3.Future<void> set(
    String? arg_key,
    Object? arg_value,
    String? arg_appGroup,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #set,
          [
            arg_key,
            arg_value,
            arg_appGroup,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> setString(
    String? arg_key,
    String? arg_value,
    String? arg_appGroup,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            arg_key,
            arg_value,
            arg_appGroup,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> setBool(
    String? arg_key,
    bool? arg_value,
    String? arg_appGroup,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            arg_key,
            arg_value,
            arg_appGroup,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> setInt(
    String? arg_key,
    int? arg_value,
    String? arg_appGroup,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            arg_key,
            arg_value,
            arg_appGroup,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> setDouble(
    String? arg_key,
    double? arg_value,
    String? arg_appGroup,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            arg_key,
            arg_value,
            arg_appGroup,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> setMap(
    String? arg_key,
    Map<Object?, Object?>? arg_value,
    String? arg_appGroup,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setMap,
          [
            arg_key,
            arg_value,
            arg_appGroup,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> remove(
    String? arg_key,
    String? arg_appGroup,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #remove,
          [
            arg_key,
            arg_appGroup,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<bool> contains(
    String? arg_key,
    String? arg_appGroup,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #contains,
          [
            arg_key,
            arg_appGroup,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
