name: widget_kit_plugin
description: A library for interfacing with a small subset of the WidgetKit API.
version: 0.0.0
homepage: https://github.com/gameflow-tv/widget_kit
repository: https://github.com/gameflow-tv/widget_kit

screenshots:
  - description: A WidgetKit illustration
    path: assets/widgetkit.png

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  pigeon: ^10.0.0
  mockito: ^5.4.1
  build_runner: ^2.4.4
  args: ^2.4.2

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: WidgetKitPlugin
      macos:
        pluginClass: WidgetKitPlugin
