name: Integration

on:
  push:
    branches: ["*"]

jobs:
  diff:
    name: diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - name: Generate pigeon stubs
        run: dart tool/gen_pigeon.dart
      - name: Validate generated pigeon stubs don't differ from committed ones
        run: dart tool/git_diff.dart -d .

  analyze:
    name: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter analyze

  test:
    name: test
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter test
